server:
  port: 8182


swagger:
  title: my swagger
  description: my good swagger
  version: 1.0

ribbon:
  eureka:
    enabled: false


ribbon-config-demo:
  ribbon:
    listOfServers: localhost:8182

feign:
  hystrix:
    enabled: false

yitu:
  service:
    url: http://localhost:8182
